services:
  - type: web
    name: carshop
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn carshop.wsgi
    staticPublishPath: static
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: carshop_project.settings
      - key: PYTHON_VERSION
        value: 3.11
