# Generated by Django 4.2.20 on 2025-04-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('kilometers', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('LPG', 'LPG'), ('CNG', 'CNG')], max_length=10)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=10)),
                ('owner_type', models.CharField(choices=[('First', 'First Owner'), ('Second', 'Second Owner')], max_length=10)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('engine', models.CharField(max_length=50)),
                ('power', models.CharField(max_length=50)),
                ('seats', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
