# Generated by Django 4.2.20 on 2025-05-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_blogpost_remove_car_serial_number_alter_car_mileage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
